name: Build Kernel for Xiaomi Pad 6 (pipa)

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dummy workspace
        uses: actions/checkout@v4

      - name: Clone pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Init pmbootstrap
        run: echo -e '\n\n' | pmbootstrap init || true

      - name: Use default pmaports and clone kernel repo
        run: |
          # Clone kernel dari GitHub branch vipaoL/dev
          git clone --depth=1 --branch vipaoL/dev https://github.com/pipa-mainline/linux.git ~/kernel-source

          # Buat tarball
          cd ~/kernel-source
          cd ..
          tar -czf linux-pipa.tar.gz kernel-source

          # Taruh tarball ke tempat pmaports nyari
          mkdir -p ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa
          cp linux-pipa.tar.gz ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa/linux-pipa.tar.gz

          # Update APKBUILD biar cocok
          APKBUILD=~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa/APKBUILD
          sed -i 's|source=.*|source="linux-pipa.tar.gz"|' "$APKBUILD"
          sed -i 's|sha512sums=.*|sha512sums="SKIP"|' "$APKBUILD"

      - name: Build kernel
        run: |
          pmbootstrap build linux-xiaomi-pipa

      - name: Upload kernel .apk
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-pipa-kernel
          path: ~/.local/var/pmbootstrap/packages/*/aarch64/linux-xiaomi-pipa-*.apk
          retention-days: 7
