name: Build Kernel Xiaomi Pad 6 (pipa)

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5' # setiap Jumat

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set up date env
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 git wget ccache libstdc++ g++ gcc apktool

      - name: Clone pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Init pmbootstrap with device non-interactive
        run: |
          printf "xiaomi-pipa\nnone\n\n" | pmbootstrap init

      - name: Replace pmaports with custom repo
        run: |
          cd ~/.local/var/pmbootstrap/cache_git
          rm -rf pmaports
          git clone --depth=1 -b v25.06 https://github.com/rifux/pipa-pmaports.git pmaports

      - name: Clone kernel source from pipa-mainline/linux vipaoL/dev
        run: |
          mkdir -p ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa
          git clone --depth=1 -b vipaoL/dev https://github.com/pipa-mainline/linux.git kernel-source
          cd kernel-source
          tar -czf ../linux-pipa.tar.gz .
          cd ..
          mv linux-pipa.tar.gz ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa/linux-pipa-initial.tar.gz

      - name: Build kernel .apk
        run: |
          pmbootstrap build linux-xiaomi-pipa
          cp ~/.local/var/pmbootstrap/packages/*/aarch64/linux-xiaomi-pipa*.apk out/

      - name: Upload kernel .apk as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-xiaomi-pipa-${{ env.DATE }}
          path: out/
          retention-days: 7
