name: Build Xiaomi Pad 6 Kernel

on:
  push:
    branches:
      - vipaoL/dev
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up environment
        run: sudo apt update && sudo apt install -y bc bison flex libssl-dev make gcc clang libc6-dev libncurses-dev ccache

      - name: Extract Kernel Source
        run: |
          mkdir -p kernel
          tar -xf linux-pipa-initial.tar.gz -C kernel --strip-components=1

      - name: Build Kernel
        run: |
          cd kernel
          make ARCH=arm64 defconfig
          make -j$(nproc) ARCH=arm64

      - name: Upload zImage
        uses: actions/upload-artifact@v4
        with:
          name: zImage
          path: kernel/arch/arm64/boot/Image

      - name: Upload dtb
        uses: actions/upload-artifact@v4
        with:
          name: dtb
          path: kernel/arch/arm64/boot/dts/qcom/*.dtb
