      - name: Clone pmaports custom
        run: |
          mkdir -p ~/.local/var/pmbootstrap/cache_git
          git clone --depth=1 https://github.com/rifux/pipa-pmaports.git ~/.local/var/pmbootstrap/cache_git/pmaports
          cd ~/.local/var/pmbootstrap/cache_git/pmaports
          git remote add origin https://gitlab.postmarketos.org/postmarketOS/pmaports.git
