# Contributor: Your Name <your@email>
# Maintainer: Your Name <your@email>
pkgname=upower
pkgver=1.90.7
pkgrel=0
pkgdesc="Power Management Daemon"
url="https://upower.freedesktop.org"
arch="all"
license="GPL-2.0-or-later"
depends="polkit dbus"
makedepends="meson ninja glib-dev libgudev-dev dbus-dev udev-dev polkit-dev"
subpackages="$pkgname-dev $pkgname-doc"
source="https://gitlab.freedesktop.org/upower/upower/-/archive/v$pkgver/upower-v$pkgver.tar.bz2"

builddir="$srcdir/$pkgname-v$pkgver"

build() {
	meson setup build \
		--prefix=/usr \
		--buildtype=release \
		-Dgtk-doc=false \
		-Dman=false \
		-Dsystemdsystemunitdir=no \
		-Dudevrulesdir=/usr/lib/udev/rules.d
	meson compile -C build
}

check() {
	meson test -C build || true
}

package() {
	DESTDIR="$pkgdir" meson install -C build
}

sha512sums="
<ISI DENGAN HASH NANTI>
"
