name: Build Kernel for Xiaomi Pad 6 (pipa)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-aarch64-linux-gnu \
            build-essential \
            bc \
            bison \
            flex \
            libssl-dev \
            libncurses-dev \
            dwarves \
            git \
            ccache \
            make \
            wget \
            curl \
            u-boot-tools \
            device-tree-compiler

      - name: Clone kernel source from pipa-mainline/linux
        run: |
          git clone --depth=1 --branch vipaoL/dev https://github.com/pipa-mainline/linux.git kernel

      - name: Build kernel
        working-directory: kernel
        run: |
          export ARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          make pipa_defconfig
          make -j$(nproc)

      - name: Upload Image.gz-dtb
        uses: actions/upload-artifact@v4
        with:
          name: kernel-image
          path: kernel/arch/arm64/boot/Image.gz-dtb
