name: Build Xiaomi Pad 6 Kernel

on:
  push:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Set current date
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 py3-pip gcc abuild ccache curl fakeroot unzip \
            alpine-sdk device-tree-compiler ncurses-dev bc bison flex openssl \
            libssl-dev elfutils-libelf-dev rsync bash

      - name: Clone pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Init pmbootstrap with dummy values
        run: |
          echo -e "\n\n" | pmbootstrap init --mirror-alpine https://mirror.alpinelinux.org/alpine/ \
            --mirror-postmarketos https://mirror.postmarketos.org/packages || true

      - name: Replace pmaports with custom repo
        run: |
          cd ~/.local/var/pmbootstrap/cache_git
          rm -rf pmaports
          git clone https://github.com/rifux/pipa-pmaports.git pmaports
          cd pmaports
          git checkout v25.06

      - name: Replace kernel source with GitHub vipaoL/dev
        run: |
          cd ~/.local/var/pmbootstrap/cache_git
          mkdir -p linux-xiaomi-pipa-custom
          git clone --depth=1 --branch vipaoL/dev https://github.com/pipa-mainline/linux.git linux-xiaomi-pipa-custom/source
          cd linux-xiaomi-pipa-custom
          tar czf linux-pipa-initial.tar.gz -C source .
          cp linux-pipa-initial.tar.gz ../pmaports/device/testing/linux-xiaomi-pipa/

      - name: Build the kernel
        run: |
          pmbootstrap build linux-xiaomi-pipa
          mkdir -p out
          cp ~/.local/var/pmbootstrap/packages/v25.06/aarch64/linux-xiaomi-pipa-*.apk out/

      - name: Upload kernel artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-xiaomi-pipa-${{ env.CURRENT_DATE }}
          path: out/*.apk
          retention-days: 14
