name: Build Xiaomi Pad 6 Kernel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: pipa-mainline/linux
        ref: vipaoL/dev
        path: kernel-src

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc ccache python3 python3-pip

    - name: Setup Clang Toolchain
      run: |
        git clone --depth=1 https://gitlab.com/AndroidDevil-Toolchains/azure-clang.git clang-llvm
        # Verifikasi toolchain
        ls clang-llvm/bin/clang || echo "Clang not found!"

    - name: Build Configuration
      run: |
        cd kernel-src
        make ARCH=arm64 O=out vendor/pipa_defconfig

    - name: Build Kernel
      run: |
        cd kernel-src
        make -j$(($(nproc) - 1)) ARCH=arm64 O=out \
          CC="$GITHUB_WORKSPACE/clang-llvm/bin/clang" \
          LD="$GITHUB_WORKSPACE/clang-llvm/bin/ld.lld" \
          AR="$GITHUB_WORKSPACE/clang-llvm/bin/llvm-ar" \
          CROSS_COMPILE="$GITHUB_WORKSPACE/clang-llvm/bin/aarch64-linux-gnu-" \
          LLVM=1 LLVM_IAS=1

    - name: List Artifacts
      run: |
        ls -la kernel-src/out/arch/arm64/boot/ || true
        ls -la kernel-src/out/vmlinux || true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-artifacts
        path: |
          kernel-src/out/arch/arm64/boot/Image
          kernel-src/out/vmlinux
