name: Build Kernel Xiaomi Pad 6

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set current date variable
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          pmbootstrap --version

      - name: Manually prepare pmaports
        run: |
          mkdir -p ~/.local/var/pmbootstrap/cache_git
          cd ~/.local/var/pmbootstrap/cache_git
          git clone --depth=1 --branch v25.06 https://github.com/rifux/pipa-pmaports.git pmaports

      - name: Build Kernel without init
        run: |
          mkdir -p ~/.config
          cp xiaomi-pipa.cfg ~/.config/pmbootstrap_v3.cfg
          pmbootstrap build linux-postmarketos-qcom-sm8250-pipa

      - name: Collect Kernel APK
        run: |
          mkdir -p out
          cp ~/.local/var/pmbootstrap/packages/v25.06/aarch64/linux-postmarketos-qcom-sm8250-pipa-*.apk out/

      - name: Upload Kernel APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xiaomi-pipa-kernel_${{ env.CURRENT_DATE }}
          path: out/*.apk
          retention-days: 14
