name: Build Xiaomi Pad 6 Kernel

on:
  workflow_dispatch:  # Memungkinkan trigger manual dari UI GitHub
  push:
    branches: [ main ]  # Otomatis jalan saat push ke branch main

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # Build kernel mungkin lama

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: pipa-mainline/linux
        ref: vipaoL/dev  # Gunakan branch spesifik
        path: kernel-src

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc ccache python3 python3-pip

    - name: Setup Clang Toolchain
      run: |
        git clone --depth=1 https://gitlab.com/AndroidDevil-Toolchains/azure-clang.git clang-llvm

    - name: Build Configuration
      run: |
        cd kernel-src
        make ARCH=arm64 O=out vendor/pipa_defconfig

    - name: Build Kernel
      run: |
        cd kernel-src
        make -j$(nproc) ARCH=arm64 O=out \
          CC=$GITHUB_WORKSPACE/clang-llvm/bin/clang \
          LD=$GITHUB_WORKSPACE/clang-llvm/bin/ld.lld \
          AR=$GITHUB_WORKSPACE/clang-llvm/bin/llvm-ar \
          CROSS_COMPILE=$GITHUB_WORKSPACE/clang-llvm/bin/aarch64-linux-gnu- \
          LLVM=1 LLVM_IAS=1

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: kernel-artifacts
        path: |
          kernel-src/out/arch/arm64/boot/Image
          kernel-src/out/vmlinux
