name: Build Xiaomi Pad 6 Kernel

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-kernel:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        repository: pipa-mainline/linux
        ref: vipaoL/dev
        path: kernel-src

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev bc ccache python3 python3-pip wget

    - name: Download AOSP Clang Toolchain
      run: |
        # Menggunakan toolchain resmi dari Android Open Source Project
        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/master/clang-r498229.tar.gz
        mkdir -p aosp-clang
        tar -xzvf clang-r498229.tar.gz -C aosp-clang
        rm clang-r498229.tar.gz

    - name: Verify Toolchain
      run: |
        ls -la aosp-clang/bin/clang
        aosp-clang/bin/clang --version || true

    - name: Build Configuration
      run: |
        cd kernel-src
        make ARCH=arm64 O=out vendor/pipa_defconfig

    - name: Build Kernel
      run: |
        cd kernel-src
        make -j$(($(nproc) - 1)) ARCH=arm64 O=out \
          CC="$GITHUB_WORKSPACE/aosp-clang/bin/clang" \
          LD="$GITHUB_WORKSPACE/aosp-clang/bin/ld.lld" \
          AR="$GITHUB_WORKSPACE/aosp-clang/bin/llvm-ar" \
          NM="$GITHUB_WORKSPACE/aosp-clang/bin/llvm-nm" \
          OBJCOPY="$GITHUB_WORKSPACE/aosp-clang/bin/llvm-objcopy" \
          OBJDUMP="$GITHUB_WORKSPACE/aosp-clang/bin/llvm-objdump" \
          STRIP="$GITHUB_WORKSPACE/aosp-clang/bin/llvm-strip" \
          CROSS_COMPILE=aarch64-linux-gnu- \
          LLVM=1 LLVM_IAS=1

    - name: Verify Build Output
      run: |
        ls -la kernel-src/out/arch/arm64/boot/ || true
        [ -f kernel-src/out/arch/arm64/boot/Image ] && echo "Kernel build successful!" || echo "Kernel file not found!"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-artifacts
        path: |
          kernel-src/out/arch/arm64/boot/Image
          kernel-src/out/vmlinux
