name: Build Xiaomi Pad 6 Kernel

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  build-kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Set current date
        run: echo "CURRENT_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3 python3-pip libglib2.0-bin squashfs-tools xz-utils \
            zip unzip wget cpio rsync curl gnupg sudo libstdc++6 device-tree-compiler

      - name: Clone pmbootstrap
        run: |
          git clone --depth=1 https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap

      - name: Clone kernel source from GitHub (vipaoL/dev)
        run: |
          git clone --depth=1 -b vipaoL/dev https://github.com/pipa-mainline/linux.git kernel-source

      - name: Init pmbootstrap
        run: |
          echo "Using non-interactive init..."
          yes "" | pmbootstrap init --no-interactive --device xiaomi-pipa --mirror-alpine https://mirror.alpinelinux.org/alpine/ --mirror-postmarketos https://mirror.postmarketos.org/packages

      - name: Replace kernel source
        run: |
          rm -rf ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa/src
          mkdir -p ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa
          cp -r kernel-source ~/.local/var/pmbootstrap/cache_git/pmaports/device/testing/linux-xiaomi-pipa/src

      - name: Build kernel
        run: |
          pmbootstrap build linux-xiaomi-pipa --no-interactive

      - name: Prepare output folder
        run: |
          mkdir -p out
          cp ~/.local/var/pmbootstrap/packages/*/aarch64/linux-xiaomi-pipa-*.apk out/

      - name: Upload kernel .apk
        uses: actions/upload-artifact@v4
        with:
          name: kernel-xiaomi-pipa-${{ env.CURRENT_DATE }}
          path: out/
          retention-days: 7
