name: Build Kernel APK for postmarketOS (Xiaomi Pad 6 - pipa)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git python3 py3-pip bash sudo
          pip3 install --upgrade pip
          pip3 install pmbootstrap

      - name: Clone pmaports
        run: |
          git clone https://github.com/pipa-mainline/pmaports.git
          cd pmaports
          git checkout vipaoL/dev

      - name: Init pmbootstrap config
        run: |
          mkdir -p ~/.config
          echo -e "architecture: aarch64\ndistribution: edge\ndevice: xiaomi-pipa\n" > ~/.config/pmbootstrap.yaml

      - name: Build kernel package
        run: |
          pmbootstrap zap --force
          pmbootstrap init --workdir "$(pwd)/pmaports" --no-keygen --device xiaomi-pipa --mirror-edge
          pmbootstrap build linux-xiaomi-pipa

      - name: Upload built .apk
        uses: actions/upload-artifact@v4
        with:
          name: kernel-apk
          path: ~/.local/var/pmbootstrap/packages/aarch64/linux-xiaomi-pipa*.apk
